### PR TITLE
Confirmation dialog before project is deleted (Fixes #739, #1000)

### LINKED ISSUE #739: Confirmation for deleting project
I think it would be great, if we'll add confirmation for deleting project. Now it can be deleted by random click...

### PR DESCRIPTION
**Pull request by steverobbins**

### CODE REVIEW

**Comment by steverobbins** [comment]
Why was this rejected?

**Comment by REBELinBLUE** [comment]
Hmm yeah @dancryer why have you rejected it? Seems rather minor change which could be quite important

**Comment by steverobbins** [comment]
It looks like the delete link (among others) was removed? https://github.com/Block8/PHPCI/blob/master/PHPCI/View/layout.phtml#L229

Or maybe it moved somewhere else.

**Comment by REBELinBLUE** [comment]
Ah yes of course, it is now a button at the top of the project details

**Pull request closed without merging**
