### PR TITLE
Build summary display

### PR DESCRIPTION
**Pull request by Adirelle**
*Contribution Type:* new feature
*Primary Area:* front-end + builder

*Description of change:*

Record and display the status of each plugin of a build, e.g.:

*Description of solution:*

* changed the plugin Executor to keep trace of each plugin execution.
* added a "summary.js" front-end plugin to display these data.

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
Oh I like that!

**Comment by cerw** [comment]
:+1:

**Comment by adamazing** [comment]
:+1:

**Comment by REBELinBLUE** [comment]
Am I being really stupid, I see this has been merged into master. I am update to date with master but it still isn't showing for me? I can see summary.js being loaded and there are AJAX requests to http://ci.aardvarklondon.com/build/meta/5574?key=plugin-summary but it just returns null each time

**Pull request closed without merging**
