### PR TITLE
Fixed 'start' string for ru lang

### PR DESCRIPTION
**Pull request by corpsee**
Fixed 'start' string for ru lang

### CODE REVIEW

**Comment by mavimo** [comment]
Google translate confirm the new string :+1:

**Comment by corpsee** [comment]
I hope I know russian a bit better than Google translate;)

**Comment by mavimo** [comment]
@corpsee I hope too, but for sure I don't know russian :)
I checked with GoogleTranslate before put the "ready-to-merge" flag just to be sure they are not "spam" string, sorry :smile:

**Comment by corpsee** [comment]
ok;)

**Comment by tvbeek** [comment]
Thanks. This pull request has been integrated manually.

**Pull request closed without merging**
