### PR TITLE
Add support to PT-BR (Brazilian Portuguese) language

### PR DESCRIPTION
**Pull request by ricardofontanelli**
Created file Languages/lang.pt-br.php

### CODE REVIEW

**Comment by atilacamurca** [comment]
Hi, @ricardofontanelli did you make the translation based on the `es` file? I'm asking because I also translate PHPCI to Brazilian portuguese (and before I send a PR I see this work already in progress) and it seems that are missing strings to translate since the file that I generate has 441 lines of code.

If you guys want I can wait and finish the missing translations after this PR is merged. What you think?

**Comment by ricardofontanelli** [comment]
Hi @atilacamurca, yes I started the translation based on the es file, but when it was finished, I noticed that some keys are not present in this file. A quick array_diff show waht keys are missing. Commit 2f12754.

**Comment by petrisrf** [comment]
This branch won't be merged to master?

**Comment by ricardofontanelli** [comment]
@Block8, is there something wrong with this PR?

**Comment by atilacamurca** [comment]
@dancryer why you close before merge? Is it something wrong?

**Comment by dancryer** [comment]
@atilacamurca There's nothing wrong with the PR as an idea, we just auto-closed all PR's as the repository was in a mess.

That said, a PT-BR language file has already been merged: https://github.com/Block8/PHPCI/blob/master/PHPCI/Languages/lang.pt-br.php - So we'd need a new PR which is based on modifying that file, rather than creating it again from scratch.

**Pull request closed without merging**
