### PR TITLE
resolving log default value issue in migration

### PR DESCRIPTION
**Pull request by th3fallen**
will resolve https://github.com/Block8/PHPCI/issues/1007 https://github.com/Block8/PHPCI/issues/977

### CODE REVIEW

**Comment by th3fallen** [comment]
not big on editing migrations once their completed but these simply will not run as they stand

**Comment by mavimo** [comment]
Migration will be always additive, we can't remove already runned migration code.

**Comment by th3fallen** [comment]
that's impossible then without removing those migrations completely then @mavimo the two migrations that where modified completely fail. unless you have another way you handle it. if so please advise.

**Comment by mavimo** [comment]
@th3fallen create a new migration using:
```
vendor/bin/phinx create MigrationName
```
the fill the methods with appropriate changes.

NB: I'm not sure remove DB constrains is the right solution, are you sure should not be fixed by set the appropriate value on the build/project entity before save it on DB?

**Comment by th3fallen** [comment]
> @th3fallen create a new migration using:

I tried that the issue is the `fix_database_columns` migration fails and blocks all further migrations from running.

**Comment by th3fallen** [comment]
any thoughts @mavimo ?

**Comment by mikebronner** [comment]
I agree with @th3fallen that at one point there were broken migrations out there that just did not work, and you could not upgrade. 

I just did a fresh install and did not encounter those issues anymore. @th3fallen are you still experiencing the issue?

**Comment by th3fallen** [comment]
I moved to something else... but i'll do another install monday and report back.

**Comment by th3fallen** [comment]
Worked for me.

**Comment by mikk150** [comment]
does not work for me, I installed mysql 5.6.27

**Pull request closed without merging**
