### PR TITLE
Adding slash in path

### PR DESCRIPTION
**Pull request by andreustimm**

### CODE REVIEW

**Comment by mikebronner** [comment]
Would it be better to use PHP's `DIRECTORY_SEPARATOR` here?

**Comment by andreustimm** [comment]
All right, I'll change.

**Comment by mikebronner** [comment]
Haha, wow, you really wen't through everything, I only meant the one instance, but that's good! :) 
:+1:

**Comment by andreustimm** [comment]
I took the opportunity to review all! :)

**Comment by andreustimm** [comment]
Approved?

**Comment by mikebronner** [comment]
Will need review by another Collaborator, like @REBELinBLUE and then merge by Dan if he thinks it fits the bill. :) As far as I'm concerned, it's good to go. :) :+1:

**Comment by tvbeek** [comment]
@mikebronner as a maintainer you could add the flag:ready-to-merge (so it is very easy to find)
I have merged it

@andreustimm Thanks for your work

**Comment by mikebronner** [comment]
@tvbeek Ah, yes, forgot about that. :)

**Comment by andreustimm** [comment]
Thanks!

**Pull request closed without merging**
