### PR TITLE
Adding output support to Behat plugin.

### PR DESCRIPTION
**Pull request by jfi**
**Contribution Type:** New Feature
**Primary Area:** Plugins
**Description of change:** Adds an output block to the Behat plugin, which lists the name of each feature file and the line number of the scenario.
**Screenshot:** Screenshot

### CODE REVIEW

**Comment by jfi** [comment]
If I try run `behat -format junit --out xml` (where an `xml` directory exists), I get the following:
 
  [Behat\Testwork\Output\Exception\FormatterNotFoundException]         
  `junit` formatter is not found or has not been properly registered.  

So it appears at the very least this isn't available out-of-the-box on OS X? https://github.com/Behat/Behat/issues/358 seems to suggest it's not implemented in 3.0 whilst https://github.com/Behat/Behat/pull/676 points to it happening any day now. I'd be happy to revisit and parse the junit output (for starters, that would mean being able to display the name of the failing scenario), but for now, I think this is the best we can do - and I'd argue, better than no output at all.

**Comment by jfi** [comment]
Additionally, I'm seeing an issue where (with 100ish scenarios), the Build Log is getting truncated half way through the tests - I assume due to the length of the database field. @mavimo, how would you or anyone else using Behat feel about changing the log output to be progress, rather than pretty, so this doesn't occur?

**Comment by mavimo** [comment]
@jfi about log length I suppose is already fixed in #777 what version of PHPCI are you using?

**Comment by jfi** [comment]
The upgrade sorted that - missed it had been merged in.

**Comment by dancryer** [comment]
Mergeded.

**Pull request closed without merging**
