### PR TITLE
Added Codeception UI plugin

### PR DESCRIPTION
**Pull request by IgorTimoshenko**
Contribution Type: new plugin, new feature
Primary Area: front-end, plugins
Link to Intent to Implement: 
Link to Bug:

Description of change: Added Codeception UI plugin

Description of solution: Created a new UI plugin named codeception, used Codeception TAP report to implement

### CODE REVIEW

**Comment by tvbeek** [comment]
I run Codeception test but with this PR I didn't see any change in the result. What should it do?

**Comment by tvbeek** [comment]
:+1: 
I like this one, have already test it local. It was something I missed so you made me happy :)

**Comment by dancryer** [comment]
Hi @IgorTimoshenko - Is there any chance you could rebase this on top of the current master branch? I'm getting some conflicts (due to other merged changes) that I don't want to chance getting wrong.

**Comment by IgorTimoshenko** [comment]
@dancryer, done :)

**Comment by tvbeek** [comment]
Merged with 55b10948efc87039c9704962ef549c7771b0855a

**Pull request closed without merging**
