### PR TITLE
Adding missing russian translations

### PR DESCRIPTION
**Pull request by sergeylunev**
Contribution Type: bug fix
Primary Area: front-end
Link to Intent to Implement: none
Link to Bug: none

Description of change: adding missing Russian translation. Also fix some other translations.

### CODE REVIEW

**Comment by corpsee** [comment]
https://github.com/Block8/PHPCI/pull/1102

**Comment by Keanor** [comment]
Очень не хватает этого мержа

**Comment by sergeylunev** [comment]
@corpsee yeah, but I also add missing translations. Or may be you mean some thing else?

@dancryer how can we merge this PR? =)

**Comment by corpsee** [comment]
@sergeylunev I mean you request duplicate #1102 (may be partialy)

**Comment by corpsee** [comment]
@Keanor, @sergeylunev I created a ["feature-fresh"](https://github.com/corpsee/PHPCI/tree/feature-fresh) branch and merging into it all pull requests with status "ready-to-merge" + some translation fixes including this request. You can use it to update your PHPCI instance at your own risk.

**Pull request closed without merging**
