### PR TITLE
Fix for strict standards issue in RebuildCommand.php

### PR DESCRIPTION
**Pull request by tankist**
[ErrorException]                                                                                                                   
Runtime Notice: Only variables should be passed by reference in /var/www/phpci/PHPCI/Command/RebuildCommand.php line 78

### CODE REVIEW

**Comment by tankist** [comment]
Is there anything I need to do that this PR could be merged???

**Comment by mavimo** [comment]
@tankist I'm waiting for a second maintainer review. I hope we will able to merge in the next weeks.

cc/ @mikebronner @jfi

**Comment by mikebronner** [comment]
:+1: Looks good to me. I have only done a code review, I don't have a test environment set up at the moment.

**Comment by mavimo** [comment]
Manually merged on 0887bd4bc4b1a74440a98b9c3667cc2a56eba0ad

**Pull request closed without merging**
